---
- name: configuration
  hosts: all
  gather_facts: false
  become: yes
  roles: 
    - commons

- name: Install HaProxy
  hosts: frontends
  gather_facts: false
  become: yes
  roles:
    - haproxy

- name: Install tomcat
  hosts: apps
  gather_facts: true
  become: yes
  roles:
    - tomcat

- name: Install Postgresql
  hosts: apps
  gather_facts: true
  roles:
    - postgres
